blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('create/', views.create_blog_view, name='create_blog'),
    path('detail/<slug>/', views.detail_blog_view, name='detail_blog'),
    path('edit/<slug>/', views.edit_blog_view, name='edit_blog')
]

myblog/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('', include('personal.urls')),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_screen_view, name='home'),
]

personal/models.py
# from django.db import models

# PRIORITY = [
#     ('L','Low'),
#     ('M','Medium'),
#     ('H','High')
# ]

# class Question(models.Model):
#     title = models.CharField(max_length=60)
#     question = models.TextField(max_length=400)
#     priority = models.CharField(max_length=1, choices=PRIORITY)

#     class Meta:
#         verbose_name = 'The Question'
#         verbose_name_plural = 'People Questions'

#     def __str__(self):
#         """Unicode representation of Question."""
#         return self.title

personal/views.py
import blog
from django.shortcuts import render
from blog.views import get_blog_queryset
from operator import attrgetter
from blog.models import BlogPost
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

BLOG_POSTS_PER_PAGE = 3

# Create your views here.
def home_screen_view(request):
    
    context = {}

    query = ""
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)

    blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)

    # Pagination
    page = request.GET.get('page', 1)
    blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)

    try:
        blog_posts = blog_posts_paginator.page(page)
    except PageNotAnInteger:
        blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
    except EmptyPage:
        blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)
    
    context['blog_posts'] = blog_posts

    return render(request, "personal/home.html", context)

personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'blog/css/home.css' %}">
<link rel="stylesheet" href="{% static 'blog/scss/test.scss' %}">
<!-- main content -->
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3 shadow-lg">
                    <img src="{% static 'company-logo.png' %}" alt="company-logo" class="company-logo" width="72" height="72">
					<p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
	  					framework and you'll see why in this course.</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create_blog' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
                        {% include 'snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->
		
		<!-- Pagination -->
		{% include 'snippets/blog_post_pagination.html' with blog_posts=blog_posts %}

		</div>
		<!-- end blog feed -->


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3 shadow-lg">
				<img src="{% static 'company-logo.png' %}" alt="company-logo" class="company-logo" width="72" height="72">
				<p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
  					framework and you'll see why in this course.</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create_blog' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->
		  
	</div>
</div>


{% endblock content %}